import {exercises,weeks,warmup,rules,milestones} from './data.js';
import {loadState,saveState,workoutKey} from './state.js';
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const state=loadState(); const byId=new Map(exercises.map(x=>[x.id,x])); let live=null,timerId=null,timerLeft=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setState(patch){Object.assign(state,patch);saveState(state);render()}
function completedCount(){return Object.values(state.completed).filter(Boolean).length}
function totalWorkouts(){return weeks.reduce((n,w)=>n+w.days.length,0)}
function currentWeek(){return weeks.find(w=>w.week===Number(state.week))||weeks[0]}
function workoutMarkup(day,i,week){const done=!!state.completed[workoutKey(week,i)];return `<article class="card workout-card" data-workout="${week}:${i}"><div class="row"><div><div class="tag">${esc(day.day)} · Workout ${i+1}</div><h3>${esc(day.name)}</h3></div><span class="pill">${done?'✓ erledigt':day.items.length+' Übungen'}</span></div><div class="small" style="margin-top:7px">${day.items.slice(0,3).map(([id])=>esc(byId.get(id)?.name||id)).join(' · ')}${day.items.length>3?' …':''}</div></article>`}
function renderHome(){const w=currentWeek(),done=w.days.filter((_,i)=>state.completed[workoutKey(w.week,i)]).length;return `<header class="header"><div><div class="kicker">ReThink.</div><h1>Calisthenics</h1><div class="small">12 Wochen · 4 Workouts/Woche</div></div><button class="icon-btn" data-action="install" aria-label="App installieren">↓</button></header><section class="card hero"><div class="small">AKTUELLE PHASE</div><div class="big">Woche ${w.week}</div><h2>${esc(w.title)}</h2><p class="small" style="margin-top:7px">${esc(w.focus)}</p><div style="margin-top:14px" class="progress-track"><div class="progress-fill" style="width:${done/4*100}%"></div></div><div class="row small" style="margin-top:7px"><span>${done}/4 diese Woche</span><span>${completedCount()}/${totalWorkouts()} gesamt</span></div></section><section class="section"><div class="section-title"><h2>Diese Woche</h2><button class="secondary" data-action="week-select">Woche wählen</button></div><div class="stack">${w.days.map((d,i)=>workoutMarkup(d,i,w.week)).join('')}</div></section><section class="section"><div class="card notice"><strong>Trainingsregel</strong><div class="small">${esc(rules[1])} Skills immer ausgeruht und technisch sauber trainieren.</div></div></section>`}
function renderPlan(){return `<header class="header"><div><div class="kicker">Programm</div><h1>12-Wochen-Plan</h1><div class="small">48 strukturierte Einheiten</div></div></header><div class="stack">${weeks.map(w=>{const done=w.days.filter((_,i)=>state.completed[workoutKey(w.week,i)]).length;return `<article class="card week-card ${w.week===Number(state.week)?'open':''}" data-week-card="${w.week}"><div class="week-head"><div class="row"><div><div class="kicker">Woche ${w.week}</div><h2>${esc(w.title)}</h2></div><span class="pill">${done}/4</span></div><p class="small" style="margin-top:6px">${esc(w.focus)}</p></div><div class="week-days">${w.days.map((d,i)=>`<div class="day-mini" data-workout="${w.week}:${i}"><div class="row"><strong>${esc(d.day)} · ${esc(d.name)}</strong><span>›</span></div><div class="small" style="margin-top:5px">${d.items.map(([id,p])=>`${esc(byId.get(id)?.name||id)} ${esc(p)}`).join(' · ')}</div></div>`).join('')}<button class="primary" data-set-week="${w.week}">Als aktuelle Woche setzen</button></div></article>`}).join('')}</div>`}
function renderExercises(){const cats=['Alle',...new Set(exercises.map(x=>x.cat))];const q=state.query.toLowerCase();const list=exercises.filter(x=>(state.exerciseFilter==='Alle'||x.cat===state.exerciseFilter)&&(!q||[x.name,x.muscles,x.equipment].join(' ').toLowerCase().includes(q)));return `<header class="header"><div><div class="kicker">Bibliothek</div><h1>Übungen</h1><div class="small">${exercises.length} Übungen mit Regression & Progression</div></div></header><div class="search"><input id="exerciseSearch" value="${esc(state.query)}" placeholder="Übung, Muskel oder Equipment suchen"></div><div class="chips">${cats.map(c=>`<button class="chip ${c===state.exerciseFilter?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="stack">${list.map(x=>`<article class="card exercise-card" data-exercise="${x.id}"><div class="row"><div><div class="kicker">${esc(x.cat)} · Level ${x.level}</div><h3>${esc(x.name)}</h3></div><span>›</span></div><div class="meta"><span class="pill">${esc(x.muscles)}</span><span class="pill">${esc(x.equipment)}</span></div></article>`).join('')||'<div class="empty">Keine Übungen gefunden.</div>'}</div>`}
function renderProgress(){const pct=Math.round(completedCount()/totalWorkouts()*100);return `<header class="header"><div><div class="kicker">Deine Entwicklung</div><h1>Fortschritt</h1></div></header><section class="card hero"><div class="row"><div><div class="small">PROGRAMM</div><div class="big">${pct}%</div></div><div style="text-align:right"><strong>${completedCount()}</strong><div class="small">von ${totalWorkouts()} Workouts</div></div></div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" style="width:${pct}%"></div></div></section><section class="section"><div class="section-title"><h2>Skill-Ziele</h2><span class="small">Tippen zum Abhaken</span></div><div class="stack">${milestones.map(m=>`<div class="card milestone ${state.milestones[m.id]?'done':''}" data-milestone="${m.id}"><button class="check">✓</button><div><strong>${esc(m.label)}</strong><div class="small">${esc(byId.get(m.exercise)?.name||'')}</div></div></div>`).join('')}</div></section><section class="section"><div class="section-title"><h2>Letzte Workouts</h2></div><div class="stack">${state.history.slice(-8).reverse().map(h=>`<div class="card"><strong>Woche ${h.week} · ${esc(h.name)}</strong><div class="small">${new Date(h.date).toLocaleDateString('de-DE')}</div></div>`).join('')||'<div class="empty">Noch kein Workout abgeschlossen.</div>'}</div></section>`}
function render(){const views={home:renderHome,plan:renderPlan,exercises:renderExercises,progress:renderProgress};$('#app').innerHTML=(views[state.view]||renderHome)();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));bind()}
function bind(){ $$('[data-view]').forEach(b=>b.onclick=()=>setState({view:b.dataset.view})); $$('[data-workout]').forEach(b=>b.onclick=e=>{e.stopPropagation();const [w,i]=b.dataset.workout.split(':').map(Number);openWorkout(w,i)}); $$('[data-week-card]').forEach(c=>$('.week-head',c).onclick=()=>c.classList.toggle('open')); $$('[data-set-week]').forEach(b=>b.onclick=e=>{e.stopPropagation();setState({week:Number(b.dataset.setWeek),view:'home'})}); $$('[data-filter]').forEach(b=>b.onclick=()=>setState({exerciseFilter:b.dataset.filter})); const s=$('#exerciseSearch');if(s)s.oninput=()=>{state.query=s.value;saveState(state);render()}; $$('[data-exercise]').forEach(b=>b.onclick=()=>openExercise(b.dataset.exercise)); $$('[data-milestone]').forEach(b=>b.onclick=()=>{state.milestones[b.dataset.milestone]=!state.milestones[b.dataset.milestone];saveState(state);render()}); const ws=$('[data-action="week-select"]');if(ws)ws.onclick=openWeekSelector; const ins=$('[data-action="install"]');if(ins)ins.onclick=installApp}
function openExercise(id){const x=byId.get(id);if(!x)return;openSheet(`<div><div class="kicker">${esc(x.cat)} · Level ${x.level}</div><h2>${esc(x.name)}</h2></div>`,`<div class="card"><div class="small">Muskeln</div><strong>${esc(x.muscles)}</strong><div class="small" style="margin-top:8px">Equipment</div><strong>${esc(x.equipment)}</strong></div><section class="section"><h3>Ausführung</h3><div class="card">${x.steps.map((s,i)=>`<div class="exercise-row"><strong>${i+1}</strong><span>${esc(s)}</span></div>`).join('')}</div></section><section class="section grid2"><div class="card"><div class="small">REGRESSION</div><strong>${esc(x.reg)}</strong></div><div class="card"><div class="small">PROGRESSION</div><strong>${esc(x.prog)}</strong></div></section><section class="section card notice"><strong>Technik-Cue</strong><div class="small">${esc(x.cue)}</div></section>`)}
function openWeekSelector(){openSheet('<h2>Aktuelle Woche</h2>',`<div class="grid2">${weeks.map(w=>`<button class="secondary" data-sheet-week="${w.week}">Woche ${w.week}</button>`).join('')}</div>`);$$('[data-sheet-week]').forEach(b=>b.onclick=()=>{state.week=Number(b.dataset.sheetWeek);saveState(state);closeSheet();render()})}
function parseSetCount(text){const m=String(text).match(/^(\d+)×/);return m?Number(m[1]):1}
function openWorkout(weekNum,index){const w=weeks.find(x=>x.week===weekNum),d=w?.days[index];if(!d)return;live={week:weekNum,index,name:d.name,checks:d.items.map(([_,p])=>Array(parseSetCount(p)).fill(false))};openSheet(`<div><div class="kicker">Woche ${weekNum} · ${esc(d.day)}</div><h2>${esc(d.name)}</h2></div>`,`<div class="card notice"><strong>Warm-up</strong><div class="small">${warmup.join(' · ')}</div></div><div class="stack" style="margin-top:10px">${d.items.map(([id,p],ei)=>{const x=byId.get(id);return `<div class="card"><div class="row"><div><div class="kicker">${esc(x?.cat||'')}</div><h3 data-live-ex="${id}" style="cursor:pointer">${esc(x?.name||id)}</h3></div><span class="pill">${esc(p)}</span></div><div>${live.checks[ei].map((done,si)=>`<div class="live-set"><button class="set-check ${done?'done':''}" data-set="${ei}:${si}">✓</button><span>Satz ${si+1}</span><span class="small">${esc(p.replace(/^\d+×/,''))}</span></div>`).join('')}</div></div>`}).join('')}</div><div class="timer"><div><div class="small">PAUSENTIMER</div><strong id="timerView">Bereit</strong></div><div><button class="secondary" data-timer="90">90 s</button> <button class="secondary" data-timer="120">120 s</button></div></div><button class="primary" style="width:100%;margin-top:12px" data-finish>Workout abschließen</button>`);$$('[data-set]').forEach(b=>b.onclick=()=>{const [ei,si]=b.dataset.set.split(':').map(Number);live.checks[ei][si]=!live.checks[ei][si];b.classList.toggle('done',live.checks[ei][si])});$$('[data-live-ex]').forEach(x=>x.onclick=()=>openExercise(x.dataset.liveEx));$$('[data-timer]').forEach(b=>b.onclick=()=>startTimer(Number(b.dataset.timer)));$('[data-finish]').onclick=finishWorkout}
function finishWorkout(){const key=workoutKey(live.week,live.index);state.completed[key]=true;if(!state.history.some(h=>h.key===key))state.history.push({key,week:live.week,name:live.name,date:new Date().toISOString()});saveState(state);closeSheet();render()}
function startTimer(sec){clearInterval(timerId);timerLeft=sec;updateTimer();timerId=setInterval(()=>{timerLeft--;updateTimer();if(timerLeft<=0){clearInterval(timerId);timerId=null}},1000)}
function updateTimer(){const v=$('#timerView');if(v)v.textContent=timerLeft>0?`${Math.floor(timerLeft/60)}:${String(timerLeft%60).padStart(2,'0')}`:'Fertig'}
function openSheet(head,body){$('#sheetRoot').innerHTML=`<div class="sheet-wrap"><div class="sheet"><div class="handle"></div><div class="sheet-top">${head}<button class="icon-btn" data-close>×</button></div>${body}</div></div>`;$('[data-close]').onclick=closeSheet;$('.sheet-wrap').onclick=e=>{if(e.target.classList.contains('sheet-wrap'))closeSheet()}}
function closeSheet(){clearInterval(timerId);timerId=null;$('#sheetRoot').innerHTML=''}
let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});async function installApp(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Im Browser-Menü „Zum Startbildschirm“ bzw. „App installieren“ wählen.')}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
