import {exercises,weeks,warmup,rules} from './data.js';
import {loadState,saveState,workoutKey} from './state.js';
import {resolveExercise as coachResolve,applyRating} from './coach.js';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state=loadState(), byId=new Map(exercises.map(x=>[x.id,x])); let live=null,timerId=null,deferredInstall=null;
function setView(view){state.view=view;saveState(state);render()}
function total(){return 48} function doneCount(){return Object.values(state.completed).filter(Boolean).length}
function nextWorkout(){for(const w of weeks)for(let i=0;i<4;i++)if(!state.completed[workoutKey(w.week,i)])return {w,i,d:w.days[i]};return null}
function currentWeekNum(){const n=nextWorkout();return n?n.w.week:12}
function resolveExercise(id){return coachResolve(id,state.adapt)}
function formatItem([id,p]){const r=resolveExercise(id),x=byId.get(r.id);return `${x?.name||r.id} · ${p}`}
function renderTraining(){const n=nextWorkout(),pct=Math.round(doneCount()/total()*100); if(!n)return `<header class="header"><div><div class="kicker">ReThink.</div><h1>Calisthenics</h1></div><button class="icon-btn" data-install>↓</button></header><section class="card hero finish"><div class="kicker">12 WOCHEN GESCHAFFT</div><div class="big">100%</div><h2>Programm abgeschlossen.</h2><p class="small">Deine 48 Einheiten sind erledigt. Wiederhole Woche 12 als Benchmark, wenn du deine aktuellen Skills erneut testen möchtest.</p><button class="primary" data-benchmark>Woche 12 öffnen</button></section>`;
 const wd=n.d,weekDone=n.w.days.filter((_,i)=>state.completed[workoutKey(n.w.week,i)]).length;return `<header class="header"><div><div class="kicker">ReThink.</div><h1>Calisthenics</h1><div class="small">12 Wochen · 4 Workouts/Woche</div></div><button class="icon-btn" data-install aria-label="App installieren">↓</button></header>
 <section class="card hero"><div class="row"><div><div class="kicker">NÄCHSTES WORKOUT</div><div class="big">W${n.w.week}.${n.i+1}</div></div><span class="pill">${doneCount()}/48</span></div><h2>${esc(wd.name)}</h2><p class="small">${esc(n.w.title)} · ${esc(n.w.focus)}</p><div class="preview">${wd.items.map(i=>`<div><span>${esc(byId.get(resolveExercise(i[0]).id)?.name||i[0])}</span><strong>${esc(i[1])}</strong></div>`).join('')}</div><button class="primary start" data-start="${n.w.week}:${n.i}">Workout starten</button></section>
 <section class="section"><div class="section-title"><h2>Woche ${n.w.week}</h2><span class="small">${weekDone}/4 erledigt</span></div><div class="progress-track"><div class="progress-fill" style="width:${weekDone*25}%"></div></div><div class="week-strip">${n.w.days.map((d,i)=>`<button class="day-dot ${state.completed[workoutKey(n.w.week,i)]?'done':''} ${i===n.i?'next':''}" data-open="${n.w.week}:${i}"><span>${esc(d.day)}</span><b>${i+1}</b></button>`).join('')}</div></section>
 <section class="section card coach"><strong>So funktioniert die Anpassung</strong><div class="small">Trainiere die Vorgabe sauber. Nach jeder Übung wählst du nur „zu schwer“, „passt“ oder „zu leicht“. Bei wiederholtem Feedback verändert die App automatisch die nächste passende Progressionsstufe.</div></section>
 <section class="section"><div class="row small"><span>Gesamtfortschritt</span><strong>${pct}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></section>`}
function renderPlan(){const cur=currentWeekNum();return `<header class="header"><div><div class="kicker">PROGRAMM</div><h1>12 Wochen</h1><div class="small">Ein Ziel: Calisthenics sauber beherrschen.</div></div></header><div class="stack">${weeks.map(w=>{const d=w.days.filter((_,i)=>state.completed[workoutKey(w.week,i)]).length;return `<article class="card week-card ${w.week===cur?'open current':''}" data-week="${w.week}"><div class="week-head"><div><div class="kicker">WOCHE ${w.week}</div><h2>${esc(w.title)}</h2><p class="small">${esc(w.focus)}</p></div><span class="pill">${d}/4</span></div><div class="week-days">${w.days.map((day,i)=>`<button class="plan-day ${state.completed[workoutKey(w.week,i)]?'done':''}" data-open="${w.week}:${i}"><div><strong>${esc(day.day)} · ${esc(day.name)}</strong><div class="small">${day.items.slice(0,3).map(formatItem).join(' · ')}${day.items.length>3?' …':''}</div></div><span>›</span></button>`).join('')}</div></article>`}).join('')}</div>`}
function render(){ $('#app').innerHTML=state.view==='plan'?renderPlan():renderTraining();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));bind() }
function bind(){ $$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-week]').forEach(c=>$('.week-head',c).onclick=()=>c.classList.toggle('open'));$$('[data-open],[data-start]').forEach(b=>b.onclick=()=>{const v=b.dataset.open||b.dataset.start,[w,i]=v.split(':').map(Number);openWorkout(w,i)});const ins=$('[data-install]');if(ins)ins.onclick=installApp;const bm=$('[data-benchmark]');if(bm)bm.onclick=()=>{state.view='plan';saveState(state);render();setTimeout(()=>document.querySelector('[data-week="12"]')?.scrollIntoView({behavior:'smooth'}),50)}}
function parseSets(p){const m=String(p).match(/^(\d+)×/);return m?Math.max(1,Number(m[1])):1}
function itemFor([baseId,p],ei,key){const r=resolveExercise(baseId),x=byId.get(r.id),saved=state.setChecks[`${key}:${ei}`]||[];return {baseId,id:r.id,x,p,changed:r.changed,family:r.family,checks:Array.from({length:parseSets(p)},(_,i)=>!!saved[i])}}
function openWorkout(weekNum,index){const w=weeks.find(x=>x.week===weekNum),d=w?.days[index];if(!d)return;const key=workoutKey(weekNum,index);live={week:weekNum,index,key,name:d.name,items:d.items.map((it,ei)=>itemFor(it,ei,key))};openSheet(`<div><div class="kicker">WOCHE ${weekNum} · ${esc(d.day)}</div><h2>${esc(d.name)}</h2></div>`,workoutBody(w,d));bindWorkout()}
function workoutBody(w,d){return `<div class="card workout-intro"><div class="small">FOKUS</div><strong>${esc(w.focus)}</strong></div><details class="warm"><summary>Warm-up · ca. 5 Minuten</summary><div class="small">${warmup.map(esc).join(' · ')}</div></details><div class="stack workout-stack">${live.items.map((it,ei)=>exerciseBlock(it,ei)).join('')}</div><div class="timer"><div><div class="small">PAUSE</div><strong id="timerView">Bereit</strong></div><div><button class="secondary mini" data-timer="90">90 s</button><button class="secondary mini" data-timer="120">120 s</button></div></div><button class="primary finish-btn" data-finish>Workout abschließen</button><p class="tiny center">${esc(rules[1])}</p>`}
function exerciseBlock(it,ei){const x=it.x;return `<article class="card live-ex"><div class="row top"><div><div class="kicker">${esc(x?.cat||'')}</div><h3 data-info="${esc(it.id)}">${esc(x?.name||it.id)}</h3></div><span class="target">${esc(it.p)}</span></div>${it.changed?`<div class="adaptive">↕ Für dich angepasst · Plan: ${esc(byId.get(it.baseId)?.name||it.baseId)}</div>`:''}<div class="cue">${esc(x?.cue||'Sauber und kontrolliert arbeiten.')}</div><div class="sets">${it.checks.map((v,si)=>`<button class="set ${v?'done':''}" data-set="${ei}:${si}">${si+1}</button>`).join('')}</div><div class="rating" data-rating-row="${ei}"><button data-rate="${ei}:-1">zu schwer</button><button data-rate="${ei}:0">passt</button><button data-rate="${ei}:1">zu leicht</button></div></article>`}
function bindWorkout(){ $$('[data-set]').forEach(b=>b.onclick=()=>{const[ei,si]=b.dataset.set.split(':').map(Number),it=live.items[ei];it.checks[si]=!it.checks[si];state.setChecks[`${live.key}:${ei}`]=it.checks;saveState(state);b.classList.toggle('done',it.checks[si])});$$('[data-rate]').forEach(b=>b.onclick=()=>{const[ei,v]=b.dataset.rate.split(':').map(Number);rateItem(ei,v);$$(`[data-rating-row="${ei}"] button`).forEach(x=>x.classList.toggle('chosen',x===b))});$$('[data-info]').forEach(b=>b.onclick=()=>openExerciseInfo(b.dataset.info));$$('[data-timer]').forEach(b=>b.onclick=()=>startTimer(Number(b.dataset.timer)));$('[data-finish]').onclick=finishWorkout}
function rateItem(ei,value){const it=live.items[ei],f=it.family;if(!f)return;const k=`${live.key}:${ei}`,prev=state.ratings[k];if(prev===value)return;state.ratings[k]=value;applyRating({family:f,value,previous:prev,ratings:state.ratings,adapt:state.adapt});saveState(state)}
function finishWorkout(){if(!live)return;state.completed[live.key]=true;for(const k of Object.keys(state.setChecks))if(k.startsWith(`${live.key}:`))delete state.setChecks[k];saveState(state);closeSheet();render()}
function openExerciseInfo(id){const x=byId.get(id);if(!x)return;const existing=$('#infoOverlay');if(existing)existing.remove();const el=document.createElement('div');el.id='infoOverlay';el.className='info-overlay';el.innerHTML=`<div class="info-card"><button class="icon-btn close-info">×</button><div class="kicker">TECHNIK</div><h2>${esc(x.name)}</h2><ol>${x.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="cue"><strong>Cue:</strong> ${esc(x.cue)}</div><div class="regprog"><div><span>Leichter</span><strong>${esc(x.reg)}</strong></div><div><span>Schwerer</span><strong>${esc(x.prog)}</strong></div></div></div>`;document.body.appendChild(el);$('.close-info',el).onclick=()=>el.remove();el.onclick=e=>{if(e.target===el)el.remove()}}
function startTimer(sec){clearInterval(timerId);let left=sec;const tick=()=>{const v=$('#timerView');if(v)v.textContent=left>0?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`:'Fertig';if(left<=0){clearInterval(timerId);timerId=null;try{navigator.vibrate?.(120)}catch{}return}left--};tick();timerId=setInterval(tick,1000)}
function openSheet(head,body){$('#sheetRoot').innerHTML=`<div class="sheet-wrap"><section class="sheet"><div class="handle"></div><div class="sheet-top">${head}<button class="icon-btn" data-close>×</button></div>${body}</section></div>`;$('[data-close]').onclick=closeSheet;$('.sheet-wrap').onclick=e=>{if(e.target.classList.contains('sheet-wrap'))closeSheet()}}
function closeSheet(){clearInterval(timerId);timerId=null;$('#sheetRoot').innerHTML='';document.querySelector('#infoOverlay')?.remove();live=null}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});async function installApp(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Im Browser-Menü „Zum Home-Bildschirm“ bzw. „App installieren“ wählen.')}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
